# Generated by Django 2.2.19 on 2023-06-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230604_1511'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='\nRepeat subscription\n',
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.UniqueConstraint(fields=('author', 'user'), name='unique_subscribe'),
        ),
    ]
